### ISSUE TITLE
Search Exploration Activity

### ISSUE THREAD

**Issue by r2roberts** [VestOfHolding/Pathfinder2EOversights#13]
I'm not sure if this is an error, but it does seem to deserve some sort of FAQ status.

p. 480 under Search Exploration Activity

> You Seek meticulously for hidden doors, concealed hazards,
> and so on. You can usually make an educated guess as to which
> locations are best to check and move at half speed, but if you
> want to be thorough and guarantee you checked everything, you
> need to travel at a Speed of no more than 300 feet per minute, or
> 150 feet per minute to ensure you check everything before you
> walk into it.

This seems very ambiguous. It mentions half speed, but then mentions 300 fpm, which is speed 30. Is that half of a speed of 60? Who has a speed of 60?  And what is with the "or 150 fpm" section?  The two clauses, 300 fpm and 150 fpm, seem to refer to the same quality of search. What is the difference between them? "Thorough and guarantee" vs.  "ensure you check everything."

The GMs section on Searching does not clarify this completely...
p. 497
> You roll a secret Perception check for a Searching
> character to detect any secrets they pass that’s in a
> place that stands out (such as near a door or a turn in
> a corridor), but not one that’s in a more inconspicuous
> place (like a random point in a long hallway) **unless they
> are searching particularly slowly and meticulously**.
> 

BTW, VoH, thank you very much for maintaining this list.  I hope you can get Paizo to take it and submit a sticky FAQ/Errata posting.

Regards,
Randy

**Comment by VestOfHolding** [comment]
Hmm, on one hand, I suspect the odd fpm range is an attempt at future proofing, which I'm ok with. On the other hand, yeah, both of those appear to be referring to the same kind of searching, I agree. Adding.

**Comment by lordcirth** [comment]
Monks can easily get a speed of 60, and there are spells that increase movespeed a lot.

**Comment by alexbrault** [comment]
The 150 fpm speed appears to be to search everything before you move past it. So 300 fpm finds all the secret doors but might make you step in a trap that moving at 150 fpm would let you spot in time.

**Comment by r2roberts** [comment]
Thanks
--
Randy M. Roberts
rsqrdroberts@gmail.com

*“The law that entropy always increases, holds, I think, the supreme
position among the laws of Nature.*
*If someone points out to you that your pet theory of the universe is in
disagreement with Maxwell's equations — then so much the worse for
Maxwell's equations.*
*If it is found to be contradicted by observation — well, these
experimentalists do bungle things sometimes.*
*But if your theory is found to be against the second law of thermodynamics
I can give you no hope;*
*there is nothing for it but to collapse in deepest humiliation.” *
― Arthur Eddington, New Pathways in Science

**Comment by VestOfHolding** [comment]
Closing as I just forgot to before. Solid discussion on this!
