### ISSUE TITLE
Bestiary, p.112

### ISSUE THREAD

**Issue by nesian42ryukaiel** [VestOfHolding/Pathfinder2EOversights#14]
The Ancient Red Dragon is Huge, not Gargantuan as it's supposed to be.

I'm quite sure one of the dev team already confirmed it as a real error in an another thread in the Paizo forums, but I want to make sure that it will be fixed ASAP in he 2nd printing, hence the reprisal here, too.

**Comment by nesian42ryukaiel** [comment]
The following link leads to James Jacobs' confirmation, just in case.

https://paizo.com/products/btq01zp4/discuss&page=5?Pathfinder-Bestiary#241

**Comment by VestOfHolding** [comment]
Added.
