### ISSUE TITLE
Bestiary: Constrict

### ISSUE THREAD

**Issue by nick1wasd** [VestOfHolding/Pathfinder2EOversights#16]
The Constrict ability states that the target must make a basic Fort Save or take the listed damage, but the monsters on pg.  94, 250, 288, 293 don't list a DC. Are these assumed to be automatic, or did someone forget to print DCs for these creatures?

**Comment by lordcirth** [comment]
Given that grappling is Athletics, I would guess it's their Athletics DC. But it should certainly be clarified.

**Comment by VestOfHolding** [comment]
Adding and closing.
