### ISSUE TITLE
CRB: Charm spell heightening

### ISSUE THREAD

**Issue by cybermephit** [VestOfHolding/Pathfinder2EOversights#18]
The Heightened entries are labeled (+4) and (+8).
This is not consistent and confusing as the effects are not cumulative.
They should be labeled (5th) and (9th) instead, assuming these are the intended levels.

**Comment by LyzLiddell** [comment]
> The Heightened entries are labeled (+4) and (+8).
> This is not consistent and confusing as the effects are not cumulative.
> They should be labeled (5th) and (9th) instead, assuming these are the intended levels.

These appear to be errors limited to the Archives of Nethys version of the spell. The _Pathfinder Core Rulebook_ lists them as intended, at **Heightened (4th)** and **Heightened (8th)**.

**Comment by VestOfHolding** [comment]
Closing as I can confirm with my own Core book. Nethys should be corrected.
