### ISSUE TITLE
Should gnomes get access to kukris

### ISSUE THREAD

**Issue by LBannenberg** [VestOfHolding/Pathfinder2EOversights#9]
Using Gnome Weaponry (https://2e.aonprd.com/Feats.aspx?ID=30) gnomes get proficiency in kukris, but not access. Kukris are uncommon though.

Every other ancestry feat that modifies proficiency in an uncommon weapon also grants access to it.

**Comment by lordcirth** [comment]
Nice catch. To clarify, while it says "In addition, you gain access to all uncommon gnome weapons", the kukri is not tagged as "gnome".
